<?php
# This file was automatically generated by the MediaWiki 1.22wmf8
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "阳光百科";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/wiki";
$wgScriptExtension = ".php";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://www.ygclub.org";

## The relative URL path to the skins directory
$wgStylePath = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo             = "http://www.ygclub.org/wiki/images/c/c6/LEAD_logo_132x50.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "kejianzu@ygclub.org";
$wgPasswordSender = "kejianzu@ygclub.org";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "";
$wgDBuser = "";
$wgDBpassword = "";

# MySQL specific settings
$wgDBprefix = "mediawiki_";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=utf8";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_MEMCACHED;
$wgMemCachedServers = array( '127.0.0.1:11211' );

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "zh";

$wgSecretKey = "d7112b6261e7ab1c33d1bf02da33ed7d1efe9caa8710eaa065a282d0ce6e931d";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "361653e4142d2080";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'cologneblue', 'monobook', 'vector':
$wgDefaultSkin = "vector";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "http://creativecommons.org/licenses/by-nc-sa/3.0/";
$wgRightsText = "知识共享署名-非商业使用-相同方式分享";
$wgRightsIcon = "{$wgStylePath}/common/images/cc-by-nc-sa.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# Query string length limit for ResourceLoader. You should only set this if
# your web server has a query string length limit (then set it to that limit),
# or if you have suhosin.get.max_value_length set in php.ini (then set it to
# that value)
$wgResourceLoaderMaxQueryLength = 512;



# End of automatically generated settings.
# Add more configuration options below.

#basic plugins
require_once( "$IP/extensions/ConfirmEdit/ConfirmEdit.php" );
require_once( "$IP/extensions/Gadgets/Gadgets.php" );
require_once( "$IP/extensions/Nuke/Nuke.php" );
require_once( "$IP/extensions/ParserFunctions/ParserFunctions.php" );
$wgPFEnableStringFunctions = true;
require_once( "$IP/extensions/Renameuser/Renameuser.php" );

#require_once( "$IP/extensions/WikiEditor/WikiEditor.php" );
## Enables use of WikiEditor by default but still allow users to disable it in preferences
#$wgDefaultUserOptions['usebetatoolbar'] = 1;
#$wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;
## Displays the Preview and Changes tabs
#$wgDefaultUserOptions['wikieditor-preview'] = 1;
## Displays the Publish and Cancel buttons on the top right side
#$wgDefaultUserOptions['wikieditor-publish'] = 0;

require_once( "$IP/extensions/ConfirmEdit/Asirra.php" );
$wgCaptchaClass = 'Asirra';
$wgGroupPermissions['user']['skipcaptcha'] = true;
$wgGroupPermissions['autoconfirmed']['skipcaptcha'] = true;

#$wgGroupPermissions['*']['createaccount'] = false;//禁止注册
$wgGroupPermissions['*'            ]['createpage'] = false;
$wgGroupPermissions['user'         ]['createpage'] = true;
$wgGroupPermissions['autoconfirmed']['createpage'] = true;
$wgAutoConfirmAge = 86400 * 4; # Four days times 86400 seconds/day

#Single Sign On
require_once( "$IP/extensions/Auth_UC/Auth_UCenter.php" );
$wgAuth = new Auth_UCenter();

$wgAllowExternalImages = true; 

$wgUsePathInfo = false;

require_once("$IP/extensions/Cite/Cite.php");
require_once("$IP/extensions/MobileFrontend/MobileFrontend.php");

require_once("$IP/extensions/videoflash.php");
$wgFileExtensions = array('sb', 'png', 'gif', 'jpg', 'jpeg' ,'rar','zip','pdf','xls','xlsx','doc','docx','ppt','pptx');
$wgAllowJavaUploads = true;

#advance plugins
require_once( "$IP/extensions/MultiBoilerplate/MultiBoilerplate.php");
$wgMultiBoilerplateDiplaySpecialPage = true;
$wgMultiBoilerplateOptions = false;
#$wgMultiBoilerplateOverwrite = true;

require_once( "$IP/extensions/DataValues/DataValues.php" );
require_once( "$IP/extensions/Validator/Validator.php" );

require_once( "$IP/extensions/Maps/Maps.php" );


require_once("$IP/extensions/VisualEditor/VisualEditor.php");
 
// OPTIONAL: Enable VisualEditor in other namespaces
// By default, VE is only enabled in NS_MAIN
//$wgVisualEditorNamespaces[] = NS_PROJECT;
 
// Enable by default for everybody
$wgDefaultUserOptions['visualeditor-enable'] = 1;
 
// Don't allow users to disable it
$wgHiddenPrefs[] = 'visualeditor-enable';
 
// OPTIONAL: Enable VisualEditor's experimental code features
//$wgVisualEditorEnableExperimentalCode = true;

$wgVisualEditorParsoidURL = 'http://localhost:8002';

$wgExternalLinkTarget = '_blank';

require_once "$IP/extensions/Scribunto/Scribunto.php";
$wgScribuntoDefaultEngine = 'luastandalone';

require_once ( "$IP/extensions/ClientsideDrafts/ClientsideDrafts.php" );

#Dynamic Page List
require_once("$IP/extensions/intersection/DynamicPageList.php");

$wgGroupPermissions['*']['upload_by_url'] = true;
$wgAllowCopyUploads = true;
$wgCopyUploadsFromSpecialUpload = true;

$wgDefaultUserOptions['timecorrection'] = '08:00';

require_once "$IP/extensions/Interwiki/Interwiki.php";
// To grant sysops permissions to edit interwiki data
$wgGroupPermissions['sysop']['interwiki'] = true;

##Start --------------------------------------- MsUpload
$wgMSU_ShowAutoKat = false;    #autocategorisation
$wgMSU_CheckedAutoKat = false;  #checkbox: checked = true/false
$wgMSU_debug = false;
$wgMSU_ImgParams = '800px'; //default max-size for image insert
require_once("$IP/extensions/MsUpload/msupload.php");
###End  --------------------------------------- MsUpload

##Start --------------------------------------- MsLinks
require_once("$IP/extensions/MsLinks/mslinks.php");
$wgMSL_FileTypes = array(
"no" => "no_icon.png",
"jpg" => "image_icon.png", 
"gif" => "image_icon.png", 
"bmp" => "image_icon.png", 
"png" => "image_icon.png", 
"tiff" => "image_icon.png", 
"tif" => "image_icon.png", 
"ai" => "image_ai_icon.png",
"psd" => "image_ps_icon.png", 
"pdf" => "pdf_icon.png", 
"pps" => "pps_icon.png", 
"ppt" => "pps_icon.png", 
"pptx" => "pps_icon.png", 
"xls" => "xls_icon.png",
"xlsx" => "xls_icon.png", 
"doc" => "doc_icon.png", 
"docx" => "doc_icon.png",
"dot" => "doc_icon.png",
"dotx" => "doc_icon.png",
"rtf" => "doc_icon.png",
"txt" => "txt_icon.png",
"html" => "code_icon.png",
"php" => "code_icon.png",
"exe" => "exe_icon.gif",
"asc" => "txt_icon.png",
"dwg" => "dwg_icon.gif",
"zip" => "zip_icon.png",
"mov"  => "movie_icon.png",
"mpeg"  => "movie_icon.png",
"mpg"  => "movie_icon.png",
"wmv"  => "movie_icon.png",
"avi"  => "movie_icon.png",
"mp4"  => "movie_icon.png",
"flv"  => "movie_flash_icon.png",
"wma"  => "music_icon.png",
"mp3"  => "music_icon.png",
"wav"  => "music_icon.png",
"mid"  => "music_icon.png"
);
##End  --------------------------------------- MsLinks

require_once( "$IP/extensions/WikiEditor/WikiEditor.php" );
require_once("$IP/extensions/WYSIWYG/WYSIWYG.php");//Activation some for all extensions
$wgGroupPermissions['*']['wysiwyg'] = true;//Everyone can use (if can edit)...
$wgDefaultUserOptions['riched_start_disabled'] = false;//Important!!! else bug...
$wgDefaultUserOptions['cke_show'] = 'richeditor';//Enable CKEditor
$wgDefaultUserOptions['riched_use_toggle'] = true;//Editor can toggle between CKEditor/WikiTextBox
$wgDefaultUserOptions['riched_start_disabled'] = false;//Important!!! else bug...
$wgDefaultUserOptions['riched_toggle_remember_state'] = true;//working/bug?)
$wgDefaultUserOptions['riched_use_popup'] = false;//Deprecated

$wgFCKEditorExcludedNamespaces[] = NS_MEDIAWIKI;
$wgFCKEditorExcludedNamespaces[] = NS_TEMPLATE;

$wgUploadSizeWarning = 10485760;
$wgMaxUploadSize = 10485760;
$wgVerifyMimeType = false;

require_once("$IP/extensions/Duoshuo/Duoshuo.php");
$wgDuoshuoShortName = 'ygwiki';
$wgDuoshuoSecret = '9d19f04122e26bddb9cca306197d7a04';

require_once("extensions/AccessControl/AccessControl.php");
$wgAccessControlMessages = true; // if set to true, show a line on top of each secured page, which says, which groups are allowed to see this page.
$wgUseMediaWikiGroups = false; // use the groups from MediaWiki instead of own Usergroup pages
$wgAdminCanReadAll = true; // sysop users can read all restricted pages

$wgRawHtml=true;
